### ISSUE TITLE
Conversion to MP4 / Ability to save to camera roll

### ISSUE THREAD

**Issue by njoye** [kaltura/playkit-dtg-ios#38]
**Is your feature request related to a problem? Please describe.**
Not really, I'd like to provide my users with an ability to save streams in their camera roll but don't see how that would be possible with the current code.

**Describe the solution you'd like**
I'd like to have an ability to "convert" (didn't fully understand HLS, sorry for that) the Downloads to some file format that can be added to the camera roll, as I don't see a way of doing that right now.

**Describe alternatives you've considered**
I didn't find anything yet, that's why I'm writing this issue.

**Additional context**
If this is not possible, then simply close it. If it is far off the goal of this project then as well, providing me with a way to find a solution to this would be awesome though, as I got lost pretty easily digging into the DTG code ... thanks!

**Comment by noamtamim** [comment]
Sorry but:
1. This is definitely not a goal for this project. The goal is to play downloaded movies in the app, not exporting them to camera roll.
2. Converting HLS to mp4 is hardly straight forward.
