### ISSUE TITLE
Getting crash in Realm

### ISSUE THREAD

**Issue by knollyReddy** [kaltura/playkit-dtg-ios#49]
**Describe the bug**

**To Reproduce**
Flow of API calls that led to the issue.

**Expected behavior**

**Logs and Screenshots**
If applicable, add log and/or screenshots to help explain your problem.

**Platform**
 - OS and version: [e.g. iOS 10.2, tvOS 11.0]
 - Device type: [e.g. iPhone, iPad]
 - Library version [e.g. 3.4.5]

**Additional context**

When I try to download video, i am getting this crash
here is my code
 do {
                    try self.cm.startItem(id: entryId)
                } catch {
                    self.toast(error.localizedDescription)
                }
Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48
	2   Realm                               0x0000000111a95b93 -[RLMRealm verifyThread] + 131
	3   Realm                               0x000000011194d446 _ZL17RLMVerifyAttachedP13RLMObjectBase + 118
	4   Realm                               0x000000011195351c _ZN12_GLOBAL__N_18getBoxedIN5realm10StringDataEEEP11objc_objectP13RLMObjectBasem + 28
	5   Realm                               0x00000001119534f7 ___ZN12_GLOBAL__N_115makeBoxedGetterIN5realm10StringDataEEEP11objc_objectm_block_invoke + 39
	6   Aurora                              0x000000010e8c10f3 $s6Aurora27ADSPFileVideoViewControllerC7addItemyyFy7PlayKit12PKMediaEntryCSg_s5Error_pSgtcfU_yycfU_ + 899
	7   Aurora                              0x000000010e27929d $sIeg_IeyB_TR + 45
	8   libdispatch.dylib                   0x00000001141f7df0 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x00000001141f8d64 _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x00000001141fb20b _dispatch_queue_override_invoke + 1022
	11  libdispatch.dylib                   0x000000011420a29a _dispatch_root_queue_drain + 351
	12  libdispatch.dylib                   0x000000011420aba4 _dispatch_worker_thread2 + 132
	13  libsystem_pthread.dylib             0x00007fff5141c6b3 _pthread_wqthread + 583
	14  libsystem_pthread.dylib             0x00007fff5141c3fd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by x-NR-x** [comment]
Hi @knollyReddy,

Thank you for contacting us.

It looks as if you're running the code not from the main thread.
You can as well check the [Example](https://github.com/kaltura/playkit-ios-dtg/tree/develop/Example) for reference.

If you still need assistance please provide me with an example code, in order for me to run it and observer the same issue.

Thanks,
Nilit Danan

**Comment by noamtamim** [comment]
@knollyReddy please reopen if it still happens.
