### ISSUE TITLE
Unable to Install Pods 

### ISSUE THREAD

**Issue by CearsKhush** [kaltura/playkit-dtg-ios#50]
Hello, 

Thank you for this awesome library, I think it provides me everything which I want but I am facing issue with Installing pods. I am unable to install the pods I am getting following errors

![Screenshot 2019-10-25 at 12 08 30 PM](https://user-images.githubusercontent.com/49678377/67548872-a160ca80-f720-11e9-8196-d9ff89b83266.png)

I had also tried to download this project and pod installation but result is same

Can you please guide me or help me with this?

Thanks :)

**Comment by x-NR-x** [comment]
Hi @CearsKhush,

Thank you for contacting us.
I'm glad to hear that you like it :)

Can you provide me with more info, so that I can observe the same.
What Xcode version are you using?
Can you share the pod file content?

Thanks,
Nilit

**Comment by CearsKhush** [comment]
Hello @x-NR-x ,

Sorry for delay and thank you so much for instant reply :)
I am using 
**Xcode 10.1
Swift 4.2**
I have created one demo project to install the pods and please check bellowed screenshot After pod installation I am getting some errors. 

![Screenshot 2019-11-04 at 9 35 16 AM](https://user-images.githubusercontent.com/49678377/68099122-d02c2d00-fee6-11e9-9fdf-bf8f8a56c959.png)

**Comment by JayCears** [comment]
Hello **@x-NR-x,**

I hope you are doing well. I facing one issue in your library.

Firstly, install pod and facing some errors then I did comment on some codes and change some values and it seems perfectly played of downloaded video online as well as offline mode.

I created a new demo and downloaded my video URL, it's played well online but not played well offline. Please check the below screenshots.

Can you give me some solutions to this issue?

![Screen Shot 2019-11-04 at 11 44 43 AM](https://user-images.githubusercontent.com/57251376/68102412-9cf29980-fef8-11e9-9028-fb9507c58d96.png)
![Screen Shot 2019-11-04 at 11 45 05 AM](https://user-images.githubusercontent.com/57251376/68102414-9f54f380-fef8-11e9-9046-2b55abc2c0db.png)
![Screen Shot 2019-11-04 at 11 44 56 AM](https://user-images.githubusercontent.com/57251376/68102416-a11eb700-fef8-11e9-88f3-6d19af151007.png)

Thanks in advance. 
:)

**Comment by x-NR-x** [comment]
Hi @CearsKhush,

From version 3.8 we support only from Swift 5, because of third party libraries.
If you still need to stay on Swift 4.2, you can use the 3.7 version.

[DTG Release Notes](https://github.com/kaltura/playkit-ios-dtg/releases)

Thanks,
Nilit Danan

**Comment by CearsKhush** [comment]
Hello @x-NR-x,

Thanks for updates :)
