### ISSUE TITLE
[Offline playback DRM] Cannot playback with castlab DRM

### ISSUE THREAD

**Issue by chinhbui** [kaltura/playkit-dtg-ios#59]
**Describe the bug**
Playback offline fairplay drm cannot play

**To Reproduce**
#EXTM3U
#EXT-X-VERSION:7
## Created with Broadpeak BkS350 Origin Packager(version=1.9.5)
#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="skd://drmtoday?assetId=LetsEat3_T02_DRM_new&variantId=",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"

# AUDIO groups
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-128",NAME="Vietnamese",LANGUAGE="vi",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-128",NAME="Korean",LANGUAGE="ko",AUTOSELECT=YES,CHANNELS="2",URI="LetsEat3_T02-audio_kor=128000.m3u8"

# variants
#EXT-X-STREAM-INF:BANDWIDTH=456000,CODECS="mp4a.40.2,avc1.4D4029",RESOLUTION=426x240,FRAME-RATE=30,AUDIO="audio-aacl-128",CLOSED-CAPTIONS=NONE
LetsEat3_T02-audio_vie=128000-video=301312.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=711000,CODECS="mp4a.40.2,avc1.4D4029",RESOLUTION=640x360,FRAME-RATE=30,AUDIO="audio-aacl-128",CLOSED-CAPTIONS=NONE
LetsEat3_T02-audio_vie=128000-video=541912.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1197000,CODECS="mp4a.40.2,avc1.4D4029",RESOLUTION=854x480,FRAME-RATE=30,AUDIO="audio-aacl-128",CLOSED-CAPTIONS=NONE
LetsEat3_T02-audio_vie=128000-video=1000440.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2260000,CODECS="mp4a.40.2,avc1.4D4029",RESOLUTION=1280x720,FRAME-RATE=30,AUDIO="audio-aacl-128",CLOSED-CAPTIONS=NONE
LetsEat3_T02-audio_vie=128000-video=2003768.m3u8

# keyframes
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=40000,CODECS="avc1.4D4029",RESOLUTION=426x240,URI="keyframes/LetsEat3_T02-video=301312.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=72000,CODECS="avc1.4D4029",RESOLUTION=640x360,URI="keyframes/LetsEat3_T02-video=541912.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=133000,CODECS="avc1.4D4029",RESOLUTION=854x480,URI="keyframes/LetsEat3_T02-video=1000440.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=266000,CODECS="avc1.4D4029",RESOLUTION=1280x720,URI="keyframes/LetsEat3_T02-video=2003768.m3u8"

 
**Error on code**
[VERBOSE] [::1:59255] ::1:59264 200 "GET /LetsEat3_T02_DRM_new/audio/cf954d982940d94245a683b8893a736b.ts" (356 | 105959)
2020-03-25 18:59:37.377 [Warning] [AVPlayerEngine+Observation.swift:90] onErrorLogEntryNotification(notification:) > error description: Optional("Segment exceeds specified bandwidth for variant"), error domain: CoreMediaErrorDomain, error code: -12318
[DEBUG] Did disconnect
[DEBUG] Did end background task
2020-03-25 18:59:49.276 [Warning] [AVPlayerEngine+Observation.swift:90] onErrorLogEntryNotification(notification:) > error description: Optional("crypt key received slowly"), error domain: CoreMediaErrorDomain, error code: -16833
2020-03-25 19:00:02.298 [Warning] [AVPlayerEngine+Observation.swift:90] onErrorLogEntryNotification(notification:) > error description: Optional("crypt key received slowly"), error domain: CoreMediaErrorDomain, error code: -16833
2020-03-25 19:00:15.340 [Debug] [AVPlayerEngine.swift:309]

**Platform**
 - OS and version: [e.g. iOS 10.2, tvOS 11.0]
 - Device type: [e.g. iPhone, iPad]
 - Library version [3.11.0]

**Comment by chinhbui** [comment]
let cerURI = "https://lic.staging.drmtoday.com/license-server-fairplay/cert/?offline=true"
        FPGetter.getCertificate(uri: cerURI) { (data, time, err) in
        } 

Cer geter:  https://gist.github.com/chinhbui/6827f58969c0ddf7a7cfa442984ba414
MyFairPlayLicenseProvider : https://gist.github.com/chinhbui/6db5003796ff152524dc814ba6c52dab

**Comment by noamtamim** [comment]
@chinhbui sorry for the delay in response. Did you resolve the issue?
If not, please first verify that the same content plays in online mode (using the same `MyFairPlayLicenseProvider` etc). 
Second, the error `"crypt key received slowly"` means just that -- it took too much time (more than a few seconds) from the time the key was requested until it was provided. It happens a lot when debugging the license retrieval process.

**Comment by chinhbui** [comment]
Hi @noamtamim , I guess problem here :
//#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="skd://drmtoday?assetId=LetsEat3_T02_DRM_new&variantId=",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"
contentId of drmtoday is "skd://drmtoday?assetId=LetsEat3_T02_DRM_new&variantId=" , meanwhile playkit return contentId is "skd://LetsEat3_T02_DRM_new" .

**Comment by amohiy** [comment]
hi @noamtamim,
i see that u mentioned this error ["crypt key received slowly"]  but i didn't get the solution. it was working fine with me and i was able to play offline after an hour it's not working and i uninstall and install the app again then downloaded another video but still getting the same error.

thanks in advance
