### ISSUE TITLE
Update RealmSwift depedency version

### ISSUE THREAD

**Issue by olliestringfield-accedo** [kaltura/playkit-dtg-ios#85]
**Is your feature request related to a problem? Please describe.**
The RealmSwift dependency is outdated at version 10.15.1

**Describe the solution you'd like**
Please update the RealmSwift dependency version to the latest release (currently, 10.32.0)

**Describe alternatives you've considered**
N/A

**Additional context**
We use RealmSwift in our app and would like to upgrade to the latest version to receive the bug fixes/enhancements provided. The current version of DownloadToGo (3.17.0) uses RealmSwift (10.7.2), this version of RealmSwift supports Xcode 12.4. The latest version supports Xcode 13 & 14

**Comment by chausov** [comment]
Hello @olliestringfield-accedo 
RealmSwift will be updated as soon as possible, but so far you may update DTG to 3.18.0 which depends on RealmSwift 10.15.1 it works with Xcode 14.

**Comment by chausov** [comment]
Hello @olliestringfield-accedo 
We are working on it, it will be updated as soon as possible.
